# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Publications
    url: publication
    weight: 50
  - name: Courses
    weight: 60
    url: courses
  # - name: "Computational Sciences: a Hands-On Approach"
  #   parent: Courses
  #   url: courses/computational-sciences-hands-on
  # - name: "Introduction to Thermodynamics and Statistical Mechanics"
  #   parent: Courses
  #   url: courses/intro-thermo-stat-mech
  - name: Software
    weight: 70
    url: software
    # url: "https://amartyabose.github.io/QuantumDynamics.jl/dev/"
    # target: _blank
  - name: News
    weight: 75
    url: news
  - name: Meet the Team
    url: people
    weight: 80
  - name: Join Us
    url: positions
    weight: 90
  - name: Contact
    url: contact
    weight: 100